FROM golang:1.14-alpine3.12 as rdslogs

WORKDIR /rdslogs

RUN apk add --no-cache git

COPY . .

RUN go mod init
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-w -s" -o rdslogs main.go


FROM golang:1.14-alpine3.12

WORKDIR /app

COPY --from=rdslogs /rdslogs/rdslogs rdslogs

ENTRYPOINT ["/app/rdslogs"]
