name: CI

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hadolint test
      run: |
        wget https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 -O hadolint
        chmod +x hadolint
        ./hadolint Dockerfile
  build:
    runs-on: ubuntu-latest
    needs: ['hadolint']
    steps:
      - uses: actions/checkout@v1

      - name: Get Image Tags
        id: get_tags
        run: |
          echo "Generating Tags for the Docker Image"
          TEMP_BRANCH=""
          if [ ${{ github.event_name }} != 'pull_request' ]; then
            TEMP_BRANCH=`echo ${GITHUB_REF} | cut -c12-`
          fi
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            TEMP_BRANCH=${GITHUB_HEAD_REF}
          fi

          BRANCH_NAME=`echo $TEMP_BRANCH | tr -s ' ' | sed -e 's/\./_/g;s/\//_/g;s/-/_/g'`
          if [ $BRANCH_NAME == "master" ]; then
            echo ::set-output name=name::$GITHUB_REPOSITORY:$BRANCH_NAME-$GITHUB_SHA, $GITHUB_REPOSITORY:$BRANCH_NAME, $GITHUB_REPOSITORY:latest
          else
            echo ::set-output name=name::$GITHUB_REPOSITORY:$BRANCH_NAME-$GITHUB_SHA, $GITHUB_REPOSITORY:$BRANCH_NAME
          fi
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.get_tags.outputs.name }}